# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'ViMeow' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

  # Pods for ViMeow
  pod 'Alamofire', '~> 4.0'
  pod 'ESPullToRefresh'
  pod 'SwiftRandom'
end
